{{ if eq .chezmoi.os "linux" }}

[".local/bin/bw"]
type = "archive-file"
url = "https://vault.bitwarden.com/download/?app=cli&platform=linux"
refreshPeriod = "168h"
executable = true
path = "bw"

[".local/bin/chezmoi"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "twpayne/chezmoi" (printf "chezmoi_*_linux_amd64.tar.gz") | quote }}
executable = true
refreshPeriod = "168h"
path = "chezmoi"

[".local/bin/chezmoi_modify_manager"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "VorpalBlade/chezmoi_modify_manager" (printf "*-x86_64-unknown-linux-gnu.tar.gz") | quote }}
executable = true
refreshPeriod = "168h"
path = "chezmoi_modify_manager"

{{ end }}