[".local/bin/bw"]
type = "archive-file"
url = "https://vault.bitwarden.com/download/?app=cli&platform=linux"
refreshPeriod = "168h"
executable = true
path = "bw"

[".local/bin/chezmoi"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "twpayne/chezmoi" (printf "chezmoi_*_linux_amd64.tar.gz") | quote }}
executable = true
refreshPeriod = "168h"
path = "chezmoi"

[".local/bin/chezmoi-modify-manager"]
type = "archive"
url = {{ gitHubLatestReleaseAssetURL "VorpalBlade/chezmoi_modify_manager" "*-i686-unknown-linux-gnu.tar.gz" | printf "%q" }}
executable = true
refreshPeriod = "168h"

[".local/bin/chezmoi-modify-manager"]
type = "archive"
url = {{ gitHubLatestReleaseAssetURL "VorpalBlade/chezmoi_modify_manager" (printf "*-%s-amd64.tar.gz" .chezmoi.os) | printf "%q" }}
executable = true
refreshPeriod = "24h"
path = "chezmoi-modify-manager"
